### ISSUE TITLE
Add supports for mutiply openvpn servers (HA mode)

### ISSUE THREAD

**Issue by mr-yaky** [linuxhq/ansible-role-openvpn_client#1]
Hi, @tkimball83 
Thanks for the this ansible role!

Can you add supports for using several "remote:" options ?

I tested and now seems that second one just not put to the config file.

**Comment by tkimball83** [comment]
Hello @mr-yaky!

How are you defining the remote option in inventory?  If you define remote as a list it should do what you're expecting.  See example below.

```
openvpn_client_options:
  remote:
    - first.remote.server.com
    - second.remote.server.com
```

**Comment by tkimball83** [comment]
I'm going to close this out @mr-yaky.  Please reopen this issue if the example above doesn't work for you.
